config/routes.rb
Rails.application.routes.draw do
  resources :routines
  resources :exercises
  resources :users
  resources :user_badges, only: [:index, :show]
  resources :badges, only: [:index, :show]

  # resources :sessions(can do this as well only instructor made custome login urls)
  get '/login',  to: 'sessions#new', as: :login
   post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :exercise
  belongs_to :user

  def self.top10(id)
    user_hash = {}
    exercise = self.all.select {|r| r.exercise_id == id}
    exercise.each do |routine|
      if user_hash[routine.user_id] == nil
        user_hash[routine.user_id] = routine.reps
      else
        user_hash[routine.user_id] += routine.reps
      end
    end
    sorted_array = user_hash.sort_by { |k,v| v }.reverse
  end


end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController

  before_action :find_routine, only: [:show, :update, :edit, :destroy]

  def index
  @routines  = Routine.all
  end

  def show

  end

  def create
    @routine = Routine.create(routine_params)
    if @routine.valid?
      UserBadge.unlocks(@routine)
      @user = User.find_by(id: params["routine"][:user_id])
      redirect_to user_path(@user)
    else
      flash[:error] = @routine.errors.full_messages
      redirect_to new_routine_path
    end
  end

  def update
      @routine = routine.find_by(id: params[:id])
      if @routine.update(routine_params)
        redirect_to user_path
      else
        flash[:errors] = @routine.errors.full_messages
        redirect_to new_routine_path
      end
  end

  def new
    @routine = Routine.new
  end

  def edit

  end

  def destroy
    @routine.destroy
    redirect_to routines_path
  end

  private

  def routine_params
    params.require(:routine).permit(:user_id, :exercise_id, :reps)
  end

  def find_routine
    @routine = Routine.find_by(id: params[:id])
  end
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/routines/edit.erb
<h1>Make Changes to Your Routine</h1>

  <%= form_for @routine do |f| %>
  <ul>
    <li><%= f.collection_select :user_id, User.all, :id, :name %></li>
    <li><%= f.collection_select :exercise_id, Exercise.all, :id, :name %></li>
  <br>
  <br> -->
  <li><%= f.label :exercise_id %></li>
  <%= f.text_field :exercise_id %>
  <br>
  <br>
  <li><%= f.label :rep %></li>
  <%= f.text_field :rep %>
  <br>
  <br>
  <li><%= f.submit %></li></ul>
<% end %>

app/views/routines/index.erb
<h1>Routines</h1>

<% @routines.each do |routine| %>

<h2><ul><li>
  <!-- Exercise: <%= link_to routine.exercise_id, exercise_path(routine.exercise_id) %> --> -->
<!-- <br> -->
<!-- User: <%= link_to routine.user_id, user_path(routine.user_id) %>
<br> -->
Rep(s): <%= link_to routine.rep, routine_path(routine) %></li></ul></h2>

<%= link_to 'Remove :)',routine, method: :delete %>

<% end %>

app/views/routines/new.erb
<div id="routine_wrapper">

<h1>Log your exercise!</h1>

<div id="routine-ui-wrapper">

  <div class="ui form">
    <%= form_for @routine do |f| %>
        <% if current_user %>
          <h3><%= current_user.username %></h3>
          <%= f.hidden_field :user_id, value: current_user.id %>
        <% end %>
      <%= f.label :exercise %>
      <%= f.collection_select :exercise_id, Exercise.all, :id, :name %>
    <br>
    <br>
    <%= f.label :reps %>
    <%= f.text_field :reps %>
    <br>
    <br>
    <%= f.submit 'Log Exercise', :class => 'ui inverted orange button'%>
    <% end %>
  </div>

</div>


</div>

app/views/routines/show.erb
<!-- <h1> About Your Routine </h1>
<ul>
<li><h2>User ID: <%= link_to @routine.user_id, user_path  %></h2></li>
<br>
<li><h2>Exercise ID: <%= link_to @routine.exercise_id, user_path %></h2></li>
<br>
<li><h2>Rep(s): <%= @routine.reps %></h2></li>
</ul>