config/routes.rb
Rails.application.routes.draw do
  resources :routines
  resources :exercises
  resources :users
  resources :user_badges, only: [:index, :show]
  resources :badges, only: [:index, :show]

  # resources :sessions(can do this as well only instructor made custome login urls)
  get '/login',  to: 'sessions#new', as: :login
   post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :routines
  has_many :exercises, through: :routines
  has_many :user_badges
  has_many :badges, through: :user_badges
  has_many :friends, through: :friendships, foreign_key: 'user_id'

  validates_length_of :password, :username, :minimum => 6
  has_secure_password


  def todays_reps(exercise_id) #sums up all reps for today for passed in exercise
    today = DateTime.now
    pushup_routines = self.routines.select {|r| r.exercise_id == exercise_id} #creates array of all routines that match exercise
    pushup_routines_week = pushup_routines.select do |r|
      r_create_time = r.created_at.in_time_zone("Eastern Time (US & Canada)")
      r_create_time.year == today.year &&
      r_create_time.month == today.month &&
      r_create_time.day == today.day
    end
    daily_reps = 0
    pushup_routines_week.each {|r| daily_reps += r.reps}
    daily_reps
  end

  def lifetime_reps(exercise_id) #sums up lifetime reps for passed in exercise
    pushup_routines = self.routines.select {|r| r.exercise_id == exercise_id}
    total_reps = 0
    pushup_routines.each {|r| total_reps += r.reps}
    total_reps
  end

  def weekly_reps(exercise_id) #sums up reps for passed in exercise performed in the past 7 days
    today = DateTime.now
    pushup_routines = self.routines.select {|r| r.exercise_id == exercise_id} #creates array of all routines that match exercise
    pushup_routines_week = pushup_routines.select {|r| r.created_at > (today - 7)}
    weekly_reps = 0
    pushup_routines_week.each {|r| weekly_reps += r.reps}
    weekly_reps
  end


  def instantiate_badges #will create a user_badge instance for all existing badges, all locked
    Badge.all.each do |badge|
      UserBadge.create(user_id: self.id, badge_id: badge.id, unlocked: false)
    end
  end

  def badges_earned #returns array of all instances of user_badge that are unlocked
    self.user_badges.select {|b| b.unlocked == true}
  end

  def badges_locked #returns array of all instances of user_badge that are unlocked
    self.user_badges.select {|b| b.unlocked == false}
  end

  def rank_array #helper method creates array in rank order
    user_hash = {}
    User.all.each do |user|
      total_reps = 0
      user.routines.each {|r| total_reps += r.reps}
      user_hash[user.id] = total_reps
    end
    sorted_array = user_hash.sort_by { |k,v| v }.reverse
  end

  def find_rank #displays the user rank as a number
    final = 0
    sorted_array = rank_array
    sorted_array.each do |ranking|
      if self.id == ranking[0]
        final = (sorted_array.find_index(ranking) + 1)
      end
    end
    final
  end



  # def self.top10(exercise_name)
  #   user_hash = {}
  #   id = Exercise.find_by(name: exercise_name)
  #   exercise = Routine.all.select {|r| r.exercise_id == exercise_id}
  #   exercise.each do |routine|
  #     if user_hash[routine.user_id] == nil
  #       user_hash[routine.user_id] = routine.reps
  #     else
  #       user_hash[routine.user_id] += routine.reps
  #     end
  #   end
  #   sorted_array = user_hash.sort_by { |k,v| v }.reverse
  # end
end #class User

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :destroy, :edit]
  skip_before_action :authorized, only: [:new, :create]

  def index
    @users = User.all
  end

  def show

  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.instantiate_badges
      flash[:notice] = "New user created successfully! Please log in!"
      redirect_to login_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def update
      @user = User.find_by(id: params[:id])
      if @user.update(user_params)
        redirect_to user_path(@user)
      else
        flash[:errors] = @user.errors.full_messages
        redirect_to user_path(@user)
      end
  end

  def new
    @user = User.new
  end

  def edit

  end

  def destroy
    @user.destroy
    redirect_to new_user_path
  end

  private

  def user_params
    params.require(:user).permit(:name,:username, :password, :weight, :mood)
  end

  def find_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.erb
  <%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :weight %>
  <%= f.text_field :weight %>
  <%= f.label :mood %>
  <%= f.text_field :mood %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.submit %>

<% end %>

app/views/users/index.erb
<div id="leaderboard_header">
    <h1>Top 10 Leaderboards</h1>
</div>

<div id="top10container">
<% Exercise.all.map { |e| e.id }.each do |id| %>
  <div class="top10item">
  <h3><%= Exercise.find_by(id: id).name %></h3>
        <ol>
        <% Routine.top10(id).each do |rank| %>
          <% user = User.find_by(id: rank[0]) %>
          <li><%= user.name %> - <%= rank[1] %></li>
          <% end %>
        </ol>
  </div>
<% end %>
  <div style="clear:both"></div>
</div>

app/views/users/new.erb
<div id="new_wrapper">
<h1>Fit Bio</h1>
<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |error| %>
    <li> <%= error %></li>
  <% end %>
</ul>
<% end %>

<div id="ui_wrapper">
  <div class="ui form">
    <%= form_for @user do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>
      <br>
      <br>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <br>
      <br>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      <br>
      <br>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <br>
      <%= f.label :'What is your fitness goal?' %>
      <%= f.text_field :mood %>
      <br>
      <br>
      <%= f.submit %>
    <% end %>
  </div>
</div>

</div>

app/views/users/show.erb
<div class="category_div" id="first_div">


  <!-- User picture -->
  <!-- absence of profile picture gallery of pictures to choose as profile pic -->

<div class="profile">
  <h3>RANK</h3>
  <p class="rank_p"># <span class="rank"><%= @user.find_rank %></span> in total reps</p>
</div>
<div class="profile">
  <h3>GOAL</h3>
  <p class="rank_p"><%= @user.mood %></p>
</div>

</div>

<div class="category_div">
  <div style="margin-bottom: 20px;">
  <h2>Today's Reps</h2>

  <button class="ui inverted orange button">
    <%= link_to "LOG NEW EXERCISE", new_routine_path %>
  </button>

  </div>
  <% @user.exercises.uniq.each do |e| %>
  <div class="exercise_div">
    <p><%= e.name.upcase %></p>
    <p><em>Reps:</em>  <span class="reps"><%= @user.todays_reps(e.id) %></span></p>
  </div>
  <% end %>
  <div style="clear:both"></div>
</div>

<div class="category_div" id="last_div">
  <h2>Rep Totals</h2>

<!-- select exercise -->

  <% @user.exercises.uniq.each do |e| %>
   <div class="exercise_div">
    <p><%= e.name.upcase %></p>
    <p><em>7 day:</em> <span class="reps"><%= @user.weekly_reps(e.id) %></span></p>
    <p><em>Lifetime:</em> <span class="reps"><%= @user.lifetime_reps(e.id) %></span></p>
   </div>
  <% end %>
  <div style="clear:both"></div>
</div>