config/routes.rb
Rails.application.routes.draw do
  resources :routines
  resources :exercises
  resources :users
  resources :user_badges, only: [:index, :show]
  resources :badges, only: [:index, :show]

  # resources :sessions(can do this as well only instructor made custome login urls)
  get '/login',  to: 'sessions#new', as: :login
   post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.erb
<div class="ui pointing menu">
 <a class="active item">
   Home
 </a>
 <a class="item">
   Messages
 </a>
 <a class="item">
   Friends
 </a>
 <div class="right menu">
   <div class="item">
     <div class="ui transparent icon input">
       <input type="text" placeholder="Search...">
       <i class="search link icon"></i>
     </div>
   </div>
 </div>
</div>
<div class="ui segment">
 <p></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GloboGym</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- semantic link -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <script
        src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    <!-- google fonts link -->
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower%7CRubik" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- semantic grid start here -->
  <div class="ui grid">
    <div class="three wide column"></div>
    <div class="ten wide column">

    <!-- container_div starts here -->
    <div id="container">
      <!-- navbar starts here -->
      <div id="navbar">

       <button class="ui inverted button">
        <% if session[:user_id] == nil %>
          <%= link_to "Profile", login_path %>
        <% else %>
          <%= link_to "Profile", user_path(session[:user_id]) %>
        <% end %>
       </button>

       <button class="ui inverted button">
         <%= link_to "Leaderboard", users_path %>
       </button>

       <button class="ui inverted button">
         <%= link_to "Badges", badges_path %>
       </button>

       <button class="ui inverted button" id="nav_right">
         <%= link_to 'Log Out', logout_path, method: :delete %>
       </button>

      </div>
      <!-- navbar ends here -->
      <div id="flash">
      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>
      </div>

      <%= yield %>

    </div>
    <!-- container_div ends here -->

    </div>
    <div class="three wide column"></div>
  </div>
  <!-- semantic grid ends here -->


  </body>
</html>